import keyMirror from 'keymirror';

export let {IMAGE_CHANGED, IMAGES_LOADED, ORIENTATION_CHANGED, FILTER_CHANGED, KEY_NAV_HAPPENED } = keyMirror({
  IMAGE_CHANGED: null,
  IMAGES_LOADED: null,
  ORIENTATION_CHANGED: null,
  FILTER_CHANGED: null,
  KEY_NAV_HAPPENED: null
});
